### ISSUE TITLE
setProxy doesn't seem to work

### ISSUE THREAD

**Issue by Froal** [meitar/libFetLife#2]
Using "auto" method or by passing a url (I took the most reliable proxy in the list, http://www.xroxy.com/proxy2682048.htm), $response['body'] (among others, but that's the most important to logIn) is empty.

**Comment by meitar** [comment]
Is the proxy actually up? ;) Empty responses are often just a timeout issue, although this library could use better error handling in that case. Using a known-good proxy does work for me.

**Comment by ShanDaDF** [comment]
would you mind giving me the proxy address you used for test? I'd like to make it work as all the ones I used didn't.

**Comment by meitar** [comment]
I just ran a test using a local proxy server I set up myself, which worked fine, and also tried the `auto` setting again, which also worked. The automatic config returned an address of `104.194.206.10:7808`, which is apparently some free proxy service? I don't know who they are. The point is, both worked for me. :\

**Comment by meitar** [comment]
Closing because works for me.
