### ISSUE TITLE
FindUserId always returns false

### ISSUE THREAD

**Issue by Froal** [meitar/libFetLife#3]
```
/**
     * Given some HTML from FetLife, this finds the current user ID.
     *
     * @param string $str Some raw HTML expected to be from FetLife.com.
     * @return mixed User ID on success. False on failure.
     */
    public function findUserId ($str) {
        $matches = array();
        preg_match('/var currentUserId = ([0-9]+);/', $str, $matches);
        return $matches[1];
    }
```

the regex seems to be wrong - that one works:

```
'/FetLife.currentUser.id          = ([0-9]+);/'
```

**Comment by meitar** [comment]
Has this been broken for you? I ask because I just added the very beginnings of a PHPUnit test harness in 173019ff980bd1a724d2ef6e9278d0a72e9e3785 and the first thing I tested was whether this was broken. It doesn't seem to be, for me. Is FetLife returning different HTML to you than me?

**Comment by ShanDaDF** [comment]
Yes it was broken. A quick search in the source code of fetlife:

```

  var showLikesSection      = false;
  FetLife                   = {};
  FetLife.currentNoticeId   = 22;
  FetLife.currentUser       = {};
  FetLife.chatPollingServer = "https://push03.fetlife.com";
  FetLife.websocketServer = "wss://rt01.fetlife.com:9393";
    FetLife.currentUser.id          = [replaced by me];
    FetLife.currentUser.nickname    = "[replaced by me]";
    FetLife.currentUser.profileUrl  = "/users/[replaced by me]";
    FetLife.currentUser.shouldPush  = false;
    FetLife.currentUser.shouldPoll  = true;
    FetLife.currentUser.shouldGetStream = true;
    FetLife.currentUser.avatar_urls = {
      mini: "[replaced by me]"
    };
    FetLife.currentUser.mostRecentBrowser              = {};
      FetLife.currentUser.mostRecentBrowser.raw_user_agent    = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36";
      FetLife.currentUser.mostRecentBrowser.raw_flash_version = "Shockwave Flash 16.0 r0";
    FetLife.currentUser.updateBrowserDetailUrl = "https://fetlife.com/users/[replaced by me]/update_browser_details";
```

But no trace of:

```
var currentUserId
```

When inspecting element in chrome/safari/ff, can you find var currentUserId?

**Comment by meitar** [comment]
Yeah, that's what's weird. I can indeed find `var currentUserId` but I can
also find `FetLife.currentUser.id`, so maybe some users are receiving
different JavaScript templates? Either way, the new regex would work for my
case as well so I'm happy to merge it with the modifications I mentioned in
the Pull Request dicussion. :)

**Comment by ShanDaDF** [comment]
:o I indeed find it on safari, but not chrome.
Anyway, as at least FetLife.currentUser.id is on all the browsers, I guess the problem is solved.
OR we could test for both, in case FetLife.currentUser.id also disappears in some browsers.
