### ISSUE TITLE
Recent Fetlife Login / Session Changes

### ISSUE THREAD

**Issue by crr** [meitar/libFetLife#9]
In the last couple weeks, changes were made on Fetlife internally that changed the way login sessions and cookies are handled, and as such it appears it has caused the entire library to break.

Attempting to get user profiles results in errors, and attempting to collect a profile's ID results in "login" instead of an integer.

**Comment by meitar** [comment]
I no longer actively maintain this library because I don't care about anything FetLife-related anymore, so you should definitely submit a pull request if you want to see this fixed. I'd be happy to apply patches but I'm not going to invest much time in this myself.

There have also been changes in the way FetLife outputs their HTML, resulting in the HTML parsing of this library to break, too. But again, ¯\_(ツ)_/¯

**Comment by meitar** [comment]
Well, I guess I should clarify that I probably *would* continue to maintain this library if it provided any benefit, academic, social, or otherwise, for me to do so. But since it doesn't, and I have other projects that I'm more interested in…yeah. :)

Anyway, "patches welcome."

**Comment by corsair** [comment]
Thank you for the swift response! I can completely understand the reasoning behind your want to not work on the project. I've been working on a project in Laravel that takes advantage of the wonderful library you set up to expand upon Fetlife's functionality in a positive manner.

After the session/login changes, I spent quite a few days attempting to resolve the issues that seem to have broken the entire script in hopes of avoiding the need for a issue, but was not successful! :cry:

If you don't have any interest in maintaining, that is completely fine though and thank you for your work thus far. I've been trying to find another developer willing to work on it with me, but thus far has been a challenge, but the search shall continue!

**Comment by meitar** [comment]
You should just fork this and push your code so I can have a look. If it looks like you're A) serious about working with someone to fix it, B) are doing something interesting with the library (show me what your idea of "expand upon FetLife's functionality in a positive manner" means to you), and C) are aligned with my personal principles (which you can read more than you probably want to know about on my blog[s]), then I'll probably enjoy working on this with you.

If you want to have a private conversation about this, send me a private email encrypted to my GPG key (see [the footer of my homepage](https://maymay.net/#ftr) for a link to it).

**Comment by meitar** [comment]
> changes were made on Fetlife internally that changed the way login sessions and cookies are handled, and as such it appears it has caused the entire library to break.
> 
> Attempting to get user profiles results in errors, and attempting to collect a profile's ID results in "login" instead of an integer.

I cannot reproduce this.

```php
require dirname(__FILE__) . '/../FetLife.php';

$FL = new FetLifeUser($username, $password);
$FL->logIn();

print "{$FL->id}\n";
```

This prints a correct ID number.
